taxi_lakehouse:
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', '/opt/airflow/data/taxi_lakehouse.duckdb') }}"
      threads: 1

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
